goal_set = [
    {'consult_id': '0',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'办理': True, '外国': True, '学习': True, '出国': True},
              'implicit_inform_slots': {'申请': True, '非公务原因': True, '届满': True, '有效期': True}}},
    {'consult_id': '1',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'签证页': True, '护照': True, '出国': True, '公民': True},
              'implicit_inform_slots': {'完毕': True, '探亲': True, '使用': True, '换发': True}}},
    {'consult_id': '2',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'护照': True, '补发': True, '普通': True, '公民': True},
              'implicit_inform_slots': {'就业': True, '办理': True, '遗失': True, '申请': True}}},
    {'consult_id': '3',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'外国': True, '签证页': True, '非公务原因': True, '普通': True},
              'implicit_inform_slots': {'护照': True, '完毕': True, '换发': True, '申请': True}}},
    {'consult_id': '4',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'护照': True, '普通': True, '签发': True, '公民': True},
              'implicit_inform_slots': {'首次': True, '办理': True, '申请': True, '非公务原因': True}}},
    {'consult_id': '5',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'申请': True, '旅行': True, '签发': True, '出国': True},
              'implicit_inform_slots': {'普通': True, '首次': True, '非公务原因': True, '公民': True}}},
    {'consult_id': '6',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'换发': True, '护照': True, '公民': True, '外国': True},
              'implicit_inform_slots': {'学习': True, '有效期': True, '届满': True, '申请': True}}},
    {'consult_id': '7',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'加注': True, '普通': True, '办理': True, '护照': True},
              'implicit_inform_slots': {'姓名': True, '外国': True, '公民': True, '姓名加注': True}}},
    {'consult_id': '8',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'出国': True, '普通': True, '换发': True, '有效期': True},
              'implicit_inform_slots': {'非公务原因': True, '办理': True, '探亲': True, '外国': True}}},
    {'consult_id': '9',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'出国': True, '非公务原因': True, '普通': True, '不能使用': True},
              'implicit_inform_slots': {'护照': True, '申请': True, '损毁': True, '补发': True}}},
    {'consult_id': '10',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'非公务原因': True, '办理': True, '护照': True, '申请': True},
              'implicit_inform_slots': {'首次': True, '外国': True, '普通': True, '签发': True}}},
    {'consult_id': '11',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名': True, '出国': True, '姓名加注': True, '申请': True},
              'implicit_inform_slots': {'英文': True, '非公务原因': True, '普通': True, '办理': True}}},
    {'consult_id': '12',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'护照': True, '申请': True, '普通': True, '旅行': True},
              'implicit_inform_slots': {'遗失': True, '公民': True, '被盗': True, '补发': True}}},
    {'consult_id': '13',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'申请': True, '签发': True, '护照': True, '普通': True},
              'implicit_inform_slots': {'非公务原因': True, '外国': True, '首次': True, '旅行': True}}},
    {'consult_id': '14',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'非公务原因': True, '普通': True, '就业': True, '外国': True},
              'implicit_inform_slots': {'首次': True, '签发': True, '护照': True, '公民': True}}},
    {'consult_id': '15',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'办理': True, '公民': True, '出国': True, '补发': True},
              'implicit_inform_slots': {'护照': True, '不能使用': True, '非公务原因': True, '损毁': True}}},
    {'consult_id': '16',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'补发': True, '商务活动': True, '办理': True, '出国': True},
              'implicit_inform_slots': {'申请': True, '被盗': True, '公民': True, '护照': True}}},
    {'consult_id': '17',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'公民': True, '申请': True, '出国': True, '外国': True},
              'implicit_inform_slots': {'护照': True, '普通': True, '签发': True, '首次': True}}},
    {'consult_id': '18',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'申请': True, '非公务原因': True, '普通': True, '出国': True},
              'implicit_inform_slots': {'签发': True, '定居': True, '首次': True, '公民': True}}},
    {'consult_id': '19',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'申请': True, '加注': True, '普通': True, '办理': True},
              'implicit_inform_slots': {'公民': True, '姓名': True, '非标准': True, '汉语': True}}},
    {'consult_id': '20',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'外国': True, '首次': True, '签发': True, '出国': True},
              'implicit_inform_slots': {'普通': True, '办理': True, '旅行': True, '非公务原因': True}}},
    {'consult_id': '21',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'外国': True, '旅行': True, '办理': True, '出国': True},
              'implicit_inform_slots': {'签发': True, '护照': True, '首次': True, '普通': True}}},
    {'consult_id': '22',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'护照': True, '探亲': True, '有效期': True, '外国': True},
              'implicit_inform_slots': {'出国': True, '届满': True, '非公务原因': True, '换发': True}}},
    {'consult_id': '23',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'非公务原因': True, '补发': True, '公民': True, '出国': True},
              'implicit_inform_slots': {'护照': True, '普通': True, '申请': True, '损毁': True}}},
    {'consult_id': '24',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'商务活动': True, '普通': True, '签证页': True, '非公务原因': True},
              'implicit_inform_slots': {'办理': True, '使用': True, '换发': True, '申请': True}}},
    {'consult_id': '25',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'不能使用': True, '就业': True, '非公务原因': True, '普通': True},
              'implicit_inform_slots': {'申请': True, '损毁': True, '办理': True, '补发': True}}},
    {'consult_id': '26',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'普通': True, '探亲': True, '公民': True, '护照': True},
              'implicit_inform_slots': {'签发': True, '申请': True, '办理': True, '首次': True}}},
    {'consult_id': '27',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'办理': True, '加注': True, '外国': True, '商务活动': True},
              'implicit_inform_slots': {'加注项': True, '出国': True, '普通': True, '曾持照加注': True}}},
    {'consult_id': '28',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'非公务原因': True, '商务活动': True, '有效期': True, '出国': True},
              'implicit_inform_slots': {'护照': True, '普通': True, '换发': True, '公民': True}}},
    {'consult_id': '29',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'公民': True, '护照': True, '普通': True, '出国': True},
              'implicit_inform_slots': {'换发': True, '完毕': True, '商务活动': True, '签证页': True}}},
    {'consult_id': '30',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'办理': True, '曾持照': True, '申请': True, '加注项': True},
              'implicit_inform_slots': {'非公务原因': True, '护照': True, '加注': True, '曾持照加注': True}}},
    {'consult_id': '31',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'外国': True, '非公务原因': True, '申请': True, '旅行': True},
              'implicit_inform_slots': {'签证页': True, '办理': True, '出国': True, '换发': True}}},
    {'consult_id': '32',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'不能使用': True, '商务活动': True, '公民': True, '普通': True},
              'implicit_inform_slots': {'损毁': True, '补发': True, '申请': True, '外国': True}}},
    {'consult_id': '33',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'出国': True, '曾持照': True, '就业': True, '普通': True},
              'implicit_inform_slots': {'加注': True, '护照': True, '外国': True, '曾持照加注': True}}},
    {'consult_id': '34',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'办理': True, '不能使用': True, '损毁': True, '普通': True},
              'implicit_inform_slots': {'出国': True, '补发': True, '护照': True, '旅行': True}}},
    {'consult_id': '35',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'使用': True, '非公务原因': True, '公民': True, '办理': True},
              'implicit_inform_slots': {'护照': True, '换发': True, '签证页': True, '完毕': True}}},
    {'consult_id': '36',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'普通': True, '签发': True, '首次': True, '申请': True},
              'implicit_inform_slots': {'公民': True, '护照': True, '办理': True, '外国': True}}},
    {'consult_id': '37',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'换发': True, '申请': True, '定居': True, '公民': True},
              'implicit_inform_slots': {'届满': True, '有效期': True, '普通': True, '办理': True}}},
    {'consult_id': '38',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'加注': True, '出国': True, '公民': True, '普通': True},
              'implicit_inform_slots': {'曾持照加注': True, '非公务原因': True, '就业': True, '曾持照': True}}},
    {'consult_id': '39',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'补发': True, '外国': True, '申请': True, '被盗': True},
              'implicit_inform_slots': {'出国': True, '探亲': True, '护照': True, '遗失': True}}},
    {'consult_id': '40',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'护照': True, '签发': True, '非公务原因': True, '首次': True},
              'implicit_inform_slots': {'定居': True, '普通': True, '出国': True, '办理': True}}},
    {'consult_id': '41',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'商务活动': True, '加注项': True, '曾持照加注': True, '加注': True},
              'implicit_inform_slots': {'公民': True, '曾持照': True, '办理': True, '出国': True}}},
    {'consult_id': '42',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'非公务原因': True, '商务活动': True, '曾持照加注': True, '公民': True},
              'implicit_inform_slots': {'办理': True, '普通': True, '出国': True, '曾持照': True}}},
    {'consult_id': '43',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'办理': True, '探亲': True, '普通': True, '签发': True},
              'implicit_inform_slots': {'申请': True, '出国': True, '首次': True, '非公务原因': True}}},
    {'consult_id': '44',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'汉字': True, '繁体': True, '公民': True, '出国': True},
              'implicit_inform_slots': {'姓名加注': True, '办理': True, '加注': True, '护照': True}}},
    {'consult_id': '45',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'普通': True, '申请': True, '学习': True, '护照': True},
              'implicit_inform_slots': {'非公务原因': True, '出国': True, '签发': True, '首次': True}}},
    {'consult_id': '46',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名加注': True, '学习': True, '外国': True, '非公务原因': True},
              'implicit_inform_slots': {'姓名': True, '多音字': True, '护照': True, '申请': True}}},
    {'consult_id': '47',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'护照': True, '非公务原因': True, '办理': True, '定居': True},
              'implicit_inform_slots': {'外国': True, '首次': True, '申请': True, '签发': True}}},
    {'consult_id': '48',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'公民': True, '非公务原因': True, '换发': True, '有效期': True},
              'implicit_inform_slots': {'护照': True, '届满': True, '办理': True, '申请': True}}},
    {'consult_id': '49',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'曾持照加注': True, '非公务原因': True, '公民': True, '办理': True},
              'implicit_inform_slots': {'申请': True, '加注': True, '曾持照': True, '护照': True}}},
    {'consult_id': '50',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'外国': True, '首次': True, '公民': True, '探亲': True},
              'implicit_inform_slots': {'非公务原因': True, '护照': True, '签发': True, '出国': True}}},
    {'consult_id': '51',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'加注': True, '汉字': True, '非公务原因': True, '姓名': True},
              'implicit_inform_slots': {'繁体': True, '出国': True, '姓名加注': True, '申请': True}}},
    {'consult_id': '52',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'普通': True, '办理': True, '非标准': True, '就业': True},
              'implicit_inform_slots': {'加注': True, '姓名加注': True, '汉语': True, '发音': True}}},
    {'consult_id': '53',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'护照': True, '首次': True, '申请': True, '公民': True},
              'implicit_inform_slots': {'普通': True, '签发': True, '非公务原因': True, '出国': True}}},
    {'consult_id': '54',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'出国': True, '繁体': True, '加注': True, '普通': True},
              'implicit_inform_slots': {'公民': True, '汉字': True, '外国': True, '非公务原因': True}}},
    {'consult_id': '55',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'申请': True, '公民': True, '旅行': True, '有效期': True},
              'implicit_inform_slots': {'护照': True, '非公务原因': True, '届满': True, '普通': True}}},
    {'consult_id': '56',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'外国': True, '办理': True, '加注': True, '护照': True},
              'implicit_inform_slots': {'英文': True, '姓名': True, '出国': True, '申请': True}}},
    {'consult_id': '57',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'办理': True, '曾持照加注': True, '非公务原因': True, '加注': True},
              'implicit_inform_slots': {'加注项': True, '申请': True, '曾持照': True, '商务活动': True}}},
    {'consult_id': '58',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'遗失': True, '出国': True, '被盗': True, '护照': True},
              'implicit_inform_slots': {'申请': True, '定居': True, '补发': True, '普通': True}}},
    {'consult_id': '59',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'办理': True, '加注': True, '非公务原因': True, '申请': True},
              'implicit_inform_slots': {'多音字': True, '姓名加注': True, '定居': True, '出国': True}}},
    {'consult_id': '60',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'护照': True, '出国': True, '有效期': True, '办理': True},
              'implicit_inform_slots': {'公民': True, '外国': True, '换发': True, '届满': True}}},
    {'consult_id': '61',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'外国': True, '护照': True, '签发': True, '定居': True},
              'implicit_inform_slots': {'出国': True, '首次': True, '办理': True, '申请': True}}},
    {'consult_id': '62',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'发音': True, '护照': True, '非标准': True, '申请': True},
              'implicit_inform_slots': {'汉语': True, '公民': True, '姓名加注': True, '外国': True}}},
    {'consult_id': '63',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'曾持照': True, '办理': True, '申请': True, '加注': True},
              'implicit_inform_slots': {'外国': True, '出国': True, '加注项': True, '公民': True}}},
    {'consult_id': '64',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'公民': True, '补发': True, '遗失': True, '护照': True},
              'implicit_inform_slots': {'商务活动': True, '外国': True, '普通': True, '被盗': True}}},
    {'consult_id': '65',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'办理': True, '出国': True, '被盗': True, '遗失': True},
              'implicit_inform_slots': {'公民': True, '护照': True, '普通': True, '非公务原因': True}}},
    {'consult_id': '66',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'被盗': True, '补发': True, '申请': True, '遗失': True},
              'implicit_inform_slots': {'办理': True, '公民': True, '外国': True, '非公务原因': True}}},
    {'consult_id': '67',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'不能使用': True, '补发': True, '出国': True, '申请': True},
              'implicit_inform_slots': {'商务活动': True, '外国': True, '损毁': True, '非公务原因': True}}},
    {'consult_id': '68',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'普通': True, '首次': True, '护照': True, '办理': True},
              'implicit_inform_slots': {'外国': True, '出国': True, '签发': True, '探亲': True}}},
    {'consult_id': '69',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'护照': True, '外国': True, '加注': True, '普通': True},
              'implicit_inform_slots': {'曾用名加注': True, '办理': True, '出国': True, '非公务原因': True}}},
    {'consult_id': '70',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'非公务原因': True, '遗失': True, '护照': True, '探亲': True},
              'implicit_inform_slots': {'外国': True, '普通': True, '公民': True, '补发': True}}},
    {'consult_id': '71',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'办理': True, '签证页': True, '完毕': True, '换发': True},
              'implicit_inform_slots': {'学习': True, '外国': True, '申请': True, '出国': True}}},
    {'consult_id': '72',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'签证页': True, '申请': True, '外国': True, '公民': True},
              'implicit_inform_slots': {'护照': True, '使用': True, '完毕': True, '非公务原因': True}}},
    {'consult_id': '73',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名': True, '加注': True, '姓名加注': True, '非公务原因': True},
              'implicit_inform_slots': {'出国': True, '发音': True, '汉语': True, '普通': True}}},
    {'consult_id': '74',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'外国': True, '公民': True, '办理': True, '签发': True},
              'implicit_inform_slots': {'普通': True, '申请': True, '首次': True, '出国': True}}},
    {'consult_id': '75',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'公民': True, '普通': True, '完毕': True, '非公务原因': True},
              'implicit_inform_slots': {'换发': True, '外国': True, '出国': True, '签证页': True}}},
    {'consult_id': '76',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'非公务原因': True, '探亲': True, '外国': True, '曾持照': True},
              'implicit_inform_slots': {'曾持照加注': True, '加注': True, '出国': True, '申请': True}}},
    {'consult_id': '77',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'护照': True, '就业': True, '公民': True, '签发': True},
              'implicit_inform_slots': {'出国': True, '首次': True, '办理': True, '申请': True}}},
    {'consult_id': '78',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'护照': True, '公民': True, '非公务原因': True, '补发': True},
              'implicit_inform_slots': {'外国': True, '不能使用': True, '办理': True, '申请': True}}},
    {'consult_id': '79',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'出国': True, '公民': True, '签证页': True, '完毕': True},
              'implicit_inform_slots': {'探亲': True, '申请': True, '换发': True, '外国': True}}},
    {'consult_id': '80',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'出国': True, '办理': True, '外国': True, '首次': True},
              'implicit_inform_slots': {'非公务原因': True, '签发': True, '商务活动': True, '护照': True}}},
    {'consult_id': '81',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'普通': True, '出国': True, '使用': True, '公民': True},
              'implicit_inform_slots': {'换发': True, '签证页': True, '护照': True, '完毕': True}}},
    {'consult_id': '82',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'首次': True, '申请': True, '公民': True, '外国': True},
              'implicit_inform_slots': {'签发': True, '探亲': True, '非公务原因': True, '出国': True}}},
    {'consult_id': '83',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'护照': True, '办理': True, '补发': True, '申请': True},
              'implicit_inform_slots': {'被盗': True, '遗失': True, '外国': True, '非公务原因': True}}},
    {'consult_id': '84',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'办理': True, '申请': True, '普通': True, '签发': True},
              'implicit_inform_slots': {'出国': True, '首次': True, '护照': True, '非公务原因': True}}},
    {'consult_id': '85',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'公民': True, '签发': True, '首次': True, '就业': True},
              'implicit_inform_slots': {'出国': True, '外国': True, '普通': True, '申请': True}}},
    {'consult_id': '86',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'申请': True, '签证页': True, '外国': True, '公民': True},
              'implicit_inform_slots': {'完毕': True, '非公务原因': True, '普通': True, '探亲': True}}},
    {'consult_id': '87',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'普通': True, '外国': True, '曾持照': True, '旅行': True},
              'implicit_inform_slots': {'曾持照加注': True, '加注': True, '办理': True, '加注项': True}}},
    {'consult_id': '88',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'加注': True, '外国': True, '曾持照加注': True, '加注项': True},
              'implicit_inform_slots': {'出国': True, '办理': True, '曾持照': True, '申请': True}}},
    {'consult_id': '89',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'出国': True, '申请': True, '外国': True, '公民': True},
              'implicit_inform_slots': {'商务活动': True, '首次': True, '护照': True, '签发': True}}},
    {'consult_id': '90',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'普通': True, '护照': True, '就业': True, '申请': True},
              'implicit_inform_slots': {'外国': True, '曾持照加注': True, '加注项': True, '曾持照': True}}},
    {'consult_id': '91',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'曾用名': True, '加注': True, '护照': True, '外国': True},
              'implicit_inform_slots': {'普通': True, '申请': True, '办理': True, '公民': True}}},
    {'consult_id': '92',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'损毁': True, '补发': True, '办理': True, '公民': True},
              'implicit_inform_slots': {'非公务原因': True, '护照': True, '出国': True, '不能使用': True}}},
    {'consult_id': '93',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'不能使用': True, '办理': True, '补发': True, '申请': True},
              'implicit_inform_slots': {'公民': True, '外国': True, '旅行': True, '损毁': True}}},
    {'consult_id': '94',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'英文': True, '就业': True, '办理': True, '姓名': True},
              'implicit_inform_slots': {'姓名加注': True, '护照': True, '申请': True, '公民': True}}},
    {'consult_id': '95',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'发音': True, '普通': True, '护照': True, '非标准': True},
              'implicit_inform_slots': {'姓名加注': True, '姓名': True, '公民': True, '汉语': True}}},
    {'consult_id': '96',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'普通': True, '公民': True, '完毕': True, '申请': True},
              'implicit_inform_slots': {'签证页': True, '外国': True, '出国': True, '办理': True}}},
    {'consult_id': '97',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'有效期': True, '旅行': True, '申请': True, '普通': True},
              'implicit_inform_slots': {'非公务原因': True, '外国': True, '届满': True, '换发': True}}},
    {'consult_id': '98',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'损毁': True, '不能使用': True, '护照': True, '非公务原因': True},
              'implicit_inform_slots': {'出国': True, '申请': True, '补发': True, '办理': True}}},
    {'consult_id': '99',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'发音': True, '公民': True, '姓名加注': True, '加注': True},
              'implicit_inform_slots': {'出国': True, '汉语': True, '外国': True, '姓名': True}}},
    {'consult_id': '100',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'探亲': True, '外国': True, '护照': True, '届满': True},
              'implicit_inform_slots': {'换发': True, '公民': True, '有效期': True, '普通': True}}},
    {'consult_id': '101',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名加注': True, '公民': True, '外国': True, '普通': True},
              'implicit_inform_slots': {'繁体': True, '护照': True, '姓名': True, '出国': True}}},
    {'consult_id': '102',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'普通': True, '首次': True, '外国': True, '非公务原因': True},
              'implicit_inform_slots': {'出国': True, '签发': True, '就业': True, '公民': True}}},
    {'consult_id': '103',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'不能使用': True, '普通': True, '补发': True, '办理': True},
              'implicit_inform_slots': {'护照': True, '非公务原因': True, '公民': True, '申请': True}}},
    {'consult_id': '104',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'补发': True, '办理': True, '出国': True, '申请': True},
              'implicit_inform_slots': {'遗失': True, '公民': True, '普通': True, '外国': True}}},
    {'consult_id': '105',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'首次': True, '公民': True, '签发': True, '外国': True},
              'implicit_inform_slots': {'出国': True, '申请': True, '护照': True, '普通': True}}},
    {'consult_id': '106',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'就业': True, '普通': True, '曾持照': True, '加注项': True},
              'implicit_inform_slots': {'曾持照加注': True, '外国': True, '加注': True, '办理': True}}},
    {'consult_id': '107',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'公民': True, '旅行': True, '办理': True, '外国': True},
              'implicit_inform_slots': {'首次': True, '签发': True, '非公务原因': True, '申请': True}}},
    {'consult_id': '108',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'外国': True, '办理': True, '护照': True, '加注': True},
              'implicit_inform_slots': {'公民': True, '汉字': True, '繁体': True, '非公务原因': True}}},
    {'consult_id': '109',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'非公务原因': True, '出国': True, '首次': True, '外国': True},
              'implicit_inform_slots': {'护照': True, '公民': True, '探亲': True, '签发': True}}},
    {'consult_id': '110',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'非公务原因': True, '办理': True, '出国': True, '遗失': True},
              'implicit_inform_slots': {'探亲': True, '申请': True, '被盗': True, '补发': True}}},
    {'consult_id': '111',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'申请': True, '出国': True, '非公务原因': True, '被盗': True},
              'implicit_inform_slots': {'补发': True, '护照': True, '遗失': True, '公民': True}}},
    {'consult_id': '112',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'学习': True, '普通': True, '不能使用': True, '补发': True},
              'implicit_inform_slots': {'申请': True, '公民': True, '护照': True, '非公务原因': True}}},
    {'consult_id': '113',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'非公务原因': True, '届满': True, '办理': True, '有效期': True},
              'implicit_inform_slots': {'旅行': True, '外国': True, '换发': True, '护照': True}}},
    {'consult_id': '114',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'有效期': True, '届满': True, '出国': True, '护照': True},
              'implicit_inform_slots': {'换发': True, '办理': True, '外国': True, '非公务原因': True}}},
    {'consult_id': '115',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名加注': True, '加注': True, '英文': True, '出国': True},
              'implicit_inform_slots': {'非公务原因': True, '办理': True, '外国': True, '公民': True}}},
    {'consult_id': '116',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'非公务原因': True, '补发': True, '外国': True, '公民': True},
              'implicit_inform_slots': {'办理': True, '护照': True, '出国': True, '遗失': True}}},
    {'consult_id': '117',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'非公务原因': True, '办理': True, '届满': True, '普通': True},
              'implicit_inform_slots': {'公民': True, '换发': True, '有效期': True, '外国': True}}},
    {'consult_id': '118',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'首次': True, '申请': True, '外国': True, '出国': True},
              'implicit_inform_slots': {'非公务原因': True, '探亲': True, '签发': True, '普通': True}}},
    {'consult_id': '119',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'外国': True, '遗失': True, '出国': True, '办理': True},
              'implicit_inform_slots': {'非公务原因': True, '公民': True, '普通': True, '被盗': True}}},
    {'consult_id': '120',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'换发': True, '办理': True, '有效期': True, '申请': True},
              'implicit_inform_slots': {'学习': True, '非公务原因': True, '公民': True, '届满': True}}},
    {'consult_id': '121',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'护照': True, '外国': True, '普通': True, '签发': True},
              'implicit_inform_slots': {'非公务原因': True, '公民': True, '首次': True, '出国': True}}},
    {'consult_id': '122',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'申请': True, '普通': True, '首次': True, '外国': True},
              'implicit_inform_slots': {'签发': True, '护照': True, '非公务原因': True, '商务活动': True}}},
    {'consult_id': '123',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'办理': True, '出国': True, '遗失': True, '被盗': True},
              'implicit_inform_slots': {'补发': True, '外国': True, '公民': True, '普通': True}}},
    {'consult_id': '124',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'办理': True, '申请': True, '出国': True, '不能使用': True},
              'implicit_inform_slots': {'外国': True, '定居': True, '损毁': True, '补发': True}}},
    {'consult_id': '125',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'护照': True, '出国': True, '申请': True, '首次': True},
              'implicit_inform_slots': {'非公务原因': True, '探亲': True, '公民': True, '签发': True}}},
    {'consult_id': '126',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'加注': True, '申请': True, '普通': True, '公民': True},
              'implicit_inform_slots': {'多音字': True, '姓名加注': True, '非公务原因': True, '姓名': True}}},
    {'consult_id': '127',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'学习': True, '普通': True, '首次': True, '办理': True},
              'implicit_inform_slots': {'非公务原因': True, '出国': True, '签发': True, '申请': True}}},
    {'consult_id': '128',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'公民': True, '非公务原因': True, '申请': True, '出国': True},
              'implicit_inform_slots': {'首次': True, '普通': True, '签发': True, '定居': True}}},
    {'consult_id': '129',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'换发': True, '届满': True, '普通': True, '有效期': True},
              'implicit_inform_slots': {'外国': True, '护照': True, '就业': True, '出国': True}}},
    {'consult_id': '130',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'签证页': True, '使用': True, '出国': True, '公民': True},
              'implicit_inform_slots': {'申请': True, '商务活动': True, '完毕': True, '外国': True}}},
    {'consult_id': '131',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'有效期': True, '公民': True, '换发': True, '申请': True},
              'implicit_inform_slots': {'商务活动': True, '出国': True, '护照': True, '办理': True}}},
    {'consult_id': '132',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'被盗': True, '遗失': True, '普通': True, '就业': True},
              'implicit_inform_slots': {'非公务原因': True, '护照': True, '申请': True, '补发': True}}},
    {'consult_id': '133',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'外国': True, '护照': True, '换发': True, '普通': True},
              'implicit_inform_slots': {'届满': True, '出国': True, '有效期': True, '非公务原因': True}}},
    {'consult_id': '134',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'外国': True, '被盗': True, '公民': True, '申请': True},
              'implicit_inform_slots': {'就业': True, '护照': True, '办理': True, '遗失': True}}},
    {'consult_id': '135',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名加注': True, '申请': True, '护照': True, '学习': True},
              'implicit_inform_slots': {'公民': True, '姓名': True, '非公务原因': True, '繁体': True}}},
    {'consult_id': '136',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'外国': True, '办理': True, '多音字': True, '姓名加注': True},
              'implicit_inform_slots': {'姓名': True, '普通': True, '出国': True, '公民': True}}},
    {'consult_id': '137',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'申请': True, '出国': True, '不能使用': True, '公民': True},
              'implicit_inform_slots': {'办理': True, '普通': True, '补发': True, '损毁': True}}},
    {'consult_id': '138',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'公民': True, '护照': True, '有效期': True, '定居': True},
              'implicit_inform_slots': {'外国': True, '届满': True, '非公务原因': True, '换发': True}}},
    {'consult_id': '139',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名': True, '加注': True, '护照': True, '英文': True},
              'implicit_inform_slots': {'姓名加注': True, '旅行': True, '出国': True, '外国': True}}},
    {'consult_id': '140',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'签发': True, '护照': True, '出国': True, '公民': True},
              'implicit_inform_slots': {'首次': True, '办理': True, '外国': True, '学习': True}}},
    {'consult_id': '141',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'学习': True, '非公务原因': True, '签发': True, '办理': True},
              'implicit_inform_slots': {'公民': True, '首次': True, '普通': True, '护照': True}}},
    {'consult_id': '142',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'申请': True, '届满': True, '外国': True, '公民': True},
              'implicit_inform_slots': {'普通': True, '护照': True, '换发': True, '非公务原因': True}}},
    {'consult_id': '143',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'遗失': True, '办理': True, '护照': True, '外国': True},
              'implicit_inform_slots': {'出国': True, '被盗': True, '补发': True, '公民': True}}},
    {'consult_id': '144',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'公民': True, '签发': True, '首次': True, '普通': True},
              'implicit_inform_slots': {'非公务原因': True, '就业': True, '出国': True, '申请': True}}},
    {'consult_id': '145',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'学习': True, '出国': True, '护照': True, '公民': True},
              'implicit_inform_slots': {'外国': True, '首次': True, '签发': True, '非公务原因': True}}},
    {'consult_id': '146',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'护照': True, '完毕': True, '非公务原因': True, '普通': True},
              'implicit_inform_slots': {'公民': True, '出国': True, '使用': True, '办理': True}}},
    {'consult_id': '147',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'非公务原因': True, '外国': True, '护照': True, '商务活动': True},
              'implicit_inform_slots': {'曾用名加注': True, '出国': True, '加注': True, '曾用名': True}}},
    {'consult_id': '148',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'被盗': True, '非公务原因': True, '办理': True, '护照': True},
              'implicit_inform_slots': {'普通': True, '补发': True, '外国': True, '遗失': True}}},
    {'consult_id': '149',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'非公务原因': True, '外国': True, '普通': True, '加注': True},
              'implicit_inform_slots': {'办理': True, '护照': True, '曾用名': True, '曾用名加注': True}}},
    {'consult_id': '150',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'姓名': True, '姓名加注': True, '非公务原因': True, '出国': True},
              'implicit_inform_slots': {'英文': True, '办理': True, '定居': True, '加注': True}}},
    {'consult_id': '151',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'普通': True, '补发': True, '非公务原因': True, '学习': True},
              'implicit_inform_slots': {'申请': True, '办理': True, '出国': True, '不能使用': True}}},
    {'consult_id': '152',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'办理': True, '普通': True, '旅行': True, '申请': True},
              'implicit_inform_slots': {'使用': True, '护照': True, '出国': True, '换发': True}}},
    {'consult_id': '153',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'汉字': True, '加注': True, '外国': True, '非公务原因': True},
              'implicit_inform_slots': {'办理': True, '出国': True, '姓名加注': True, '繁体': True}}},
    {'consult_id': '154',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'公民': True, '出国': True, '首次': True, '签发': True},
              'implicit_inform_slots': {'外国': True, '普通': True, '护照': True, '办理': True}}},
    {'consult_id': '155',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'护照': True, '出国': True, '届满': True, '申请': True},
              'implicit_inform_slots': {'非公务原因': True, '有效期': True, '办理': True, '换发': True}}},
    {'consult_id': '156',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'曾持照': True, '曾持照加注': True, '办理': True, '公民': True},
              'implicit_inform_slots': {'外国': True, '申请': True, '护照': True, '加注项': True}}},
    {'consult_id': '157',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'不能使用': True, '损毁': True, '外国': True, '护照': True},
              'implicit_inform_slots': {'申请': True, '办理': True, '出国': True, '非公务原因': True}}},
    {'consult_id': '158',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'繁体': True, '出国': True, '汉字': True, '姓名加注': True},
              'implicit_inform_slots': {'护照': True, '普通': True, '加注': True, '学习': True}}},
    {'consult_id': '159',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'签发': True, '出国': True, '公民': True, '非公务原因': True},
              'implicit_inform_slots': {'普通': True, '首次': True, '申请': True, '探亲': True}}},
    {'consult_id': '160',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'完毕': True, '非公务原因': True, '申请': True, '公民': True},
              'implicit_inform_slots': {'使用': True, '签证页': True, '外国': True, '出国': True}}},
    {'consult_id': '161',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'签发': True, '外国': True, '非公务原因': True, '首次': True},
              'implicit_inform_slots': {'护照': True, '办理': True, '商务活动': True, '公民': True}}},
    {'consult_id': '162',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'完毕': True, '护照': True, '探亲': True, '申请': True},
              'implicit_inform_slots': {'换发': True, '办理': True, '签证页': True, '普通': True}}},
    {'consult_id': '163',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'届满': True, '办理': True, '护照': True, '公民': True},
              'implicit_inform_slots': {'探亲': True, '有效期': True, '换发': True, '非公务原因': True}}},
    {'consult_id': '164',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'被盗': True, '就业': True, '护照': True, '补发': True},
              'implicit_inform_slots': {'公民': True, '外国': True, '申请': True, '办理': True}}},
    {'consult_id': '165',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'出国': True, '届满': True, '办理': True, '换发': True},
              'implicit_inform_slots': {'护照': True, '公民': True, '有效期': True, '旅行': True}}},
    {'consult_id': '166',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'首次': True, '旅行': True, '申请': True, '出国': True},
              'implicit_inform_slots': {'公民': True, '外国': True, '办理': True, '签发': True}}},
    {'consult_id': '167',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'非公务原因': True, '发音': True, '加注': True, '姓名加注': True},
              'implicit_inform_slots': {'非标准': True, '姓名': True, '普通': True, '汉语': True}}},
    {'consult_id': '168',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'探亲': True, '非公务原因': True, '出国': True, '届满': True},
              'implicit_inform_slots': {'办理': True, '换发': True, '护照': True, '公民': True}}},
    {'consult_id': '169',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'旅行': True, '签发': True, '办理': True, '首次': True},
              'implicit_inform_slots': {'外国': True, '公民': True, '出国': True, '普通': True}}},
    {'consult_id': '170',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'公民': True, '损毁': True, '普通': True, '出国': True},
              'implicit_inform_slots': {'办理': True, '不能使用': True, '非公务原因': True, '申请': True}}},
    {'consult_id': '171',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'外国': True, '出国': True, '办理': True, '公民': True},
              'implicit_inform_slots': {'非公务原因': True, '加注': True, '加注项': True, '曾持照加注': True}}},
    {'consult_id': '172',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'护照': True, '外国': True, '办理': True, '曾用名加注': True},
              'implicit_inform_slots': {'申请': True, '出国': True, '曾用名': True, '公民': True}}},
    {'consult_id': '173',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'非公务原因': True, '申请': True, '首次': True, '护照': True},
              'implicit_inform_slots': {'签发': True, '定居': True, '办理': True, '公民': True}}},
    {'consult_id': '174',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'办理': True, '非公务原因': True, '首次': True, '签发': True},
              'implicit_inform_slots': {'旅行': True, '申请': True, '外国': True, '出国': True}}},
    {'consult_id': '175',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'普通': True, '签发': True, '出国': True, '首次': True},
              'implicit_inform_slots': {'商务活动': True, '办理': True, '护照': True, '申请': True}}},
    {'consult_id': '176',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'非公务原因': True, '护照': True, '就业': True, '申请': True},
              'implicit_inform_slots': {'首次': True, '外国': True, '签发': True, '普通': True}}},
    {'consult_id': '177',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'使用': True, '完毕': True, '出国': True, '非公务原因': True},
              'implicit_inform_slots': {'普通': True, '签证页': True, '外国': True, '换发': True}}},
    {'consult_id': '178',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'护照': True, '普通': True, '非公务原因': True, '商务活动': True},
              'implicit_inform_slots': {'办理': True, '被盗': True, '补发': True, '公民': True}}},
    {'consult_id': '179',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'商务活动': True, '签证页': True, '使用': True, '换发': True},
              'implicit_inform_slots': {'公民': True, '非公务原因': True, '普通': True, '出国': True}}},
    {'consult_id': '180',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'商务活动': True, '签发': True, '护照': True, '公民': True},
              'implicit_inform_slots': {'申请': True, '外国': True, '非公务原因': True, '首次': True}}},
    {'consult_id': '181',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'公民': True, '加注': True, '外国': True, '发音': True},
              'implicit_inform_slots': {'汉语': True, '护照': True, '办理': True, '非标准': True}}},
    {'consult_id': '182',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'多音字': True, '公民': True, '外国': True, '姓名': True},
              'implicit_inform_slots': {'加注': True, '姓名加注': True, '办理': True, '出国': True}}},
    {'consult_id': '183',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'非公务原因': True, '姓名': True, '护照': True, '普通': True},
              'implicit_inform_slots': {'姓名加注': True, '办理': True, '加注': True, '商务活动': True}}},
    {'consult_id': '184',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'公民': True, '护照': True, '办理': True, '加注': True},
              'implicit_inform_slots': {'曾用名': True, '旅行': True, '申请': True, '非公务原因': True}}},
    {'consult_id': '185',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'护照': True, '外国': True, '非公务原因': True, '损毁': True},
              'implicit_inform_slots': {'出国': True, '补发': True, '不能使用': True, '就业': True}}},
    {'consult_id': '186',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'申请': True, '办理': True, '出国': True, '普通': True},
              'implicit_inform_slots': {'签发': True, '非公务原因': True, '外国': True, '首次': True}}},
    {'consult_id': '187',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'使用': True, '完毕': True, '普通': True, '外国': True},
              'implicit_inform_slots': {'换发': True, '出国': True, '公民': True, '护照': True}}},
    {'consult_id': '188',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'外国': True, '普通': True, '出国': True, '届满': True},
              'implicit_inform_slots': {'申请': True, '换发': True, '商务活动': True, '公民': True}}},
    {'consult_id': '189',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'遗失': True, '出国': True, '普通': True, '公民': True},
              'implicit_inform_slots': {'学习': True, '补发': True, '办理': True, '被盗': True}}},
    {'consult_id': '190',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'申请': True, '普通': True, '出国': True, '护照': True},
              'implicit_inform_slots': {'补发': True, '公民': True, '外国': True, '损毁': True}}},
    {'consult_id': '191',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'换发': True, '非公务原因': True, '完毕': True, '出国': True},
              'implicit_inform_slots': {'使用': True, '护照': True, '就业': True, '签证页': True}}},
    {'consult_id': '192',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'首次': True, '普通': True, '签发': True, '办理': True},
              'implicit_inform_slots': {'出国': True, '公民': True, '外国': True, '申请': True}}},
    {'consult_id': '193',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'签发': True, '普通': True, '首次': True, '申请': True},
              'implicit_inform_slots': {'护照': True, '非公务原因': True, '外国': True, '办理': True}}},
    {'consult_id': '194',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'换发护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--换发护照',
              'explicit_inform_slots': {'公民': True, '定居': True, '办理': True, '有效期': True},
              'implicit_inform_slots': {'护照': True, '普通': True, '换发': True, '申请': True}}},
    {'consult_id': '195',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'首次申请护照': True},
              'service_tag': '普通护照签发、换发、补发及加注--首次申请护照',
              'explicit_inform_slots': {'学习': True, '出国': True, '非公务原因': True, '护照': True},
              'implicit_inform_slots': {'公民': True, '签发': True, '普通': True, '首次': True}}},
    {'consult_id': '196',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照加注': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照加注',
              'explicit_inform_slots': {'办理': True, '汉字': True, '非公务原因': True, '护照': True},
              'implicit_inform_slots': {'外国': True, '加注': True, '姓名': True, '姓名加注': True}}},
    {'consult_id': '197',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'损毁': True, '出国': True, '旅行': True, '办理': True},
              'implicit_inform_slots': {'外国': True, '护照': True, '公民': True, '补发': True}}},
    {'consult_id': '198',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'补发': True, '定居': True, '普通': True, '外国': True},
              'implicit_inform_slots': {'非公务原因': True, '护照': True, '办理': True, '遗失': True}}},
    {'consult_id': '199',
     'goal': {'request_slots': {'service': 'UNK'},
              'max_slot': {'护照补发': True},
              'service_tag': '普通护照签发、换发、补发及加注--护照补发',
              'explicit_inform_slots': {'公民': True, '外国': True, '就业': True, '出国': True},
              'implicit_inform_slots': {'普通': True, '被盗': True, '护照': True, '遗失': True}}}
]
